// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
   
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
     
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC15KPodTdtX6wypX1HqSDL05d307lV-N0',
    appId: '1:110847233469:android:89a333f438601a3b4a96d4',
    messagingSenderId: '110847233469',
    projectId: 'docdoc-app-5076f',
    storageBucket: 'docdoc-app-5076f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy5AEZaYpRimrqg2sYJC_tXHlkCNAieO4',
    appId: '1:110847233469:ios:81fbb3edcf65a6854a96d4',
    messagingSenderId: '110847233469',
    projectId: 'docdoc-app-5076f',
    storageBucket: 'docdoc-app-5076f.appspot.com',
    iosBundleId: 'com.example.advancedCourse',
  );

 
}
